system:
  debug: True
  secret: RZ1PcBzqbfQ9fkVqXWLiS4ZyeXihVYIN
  prefix: /api/v1
  port: 8090
  login_url:
  static: uploads
  templates:
  static_url_prefix: /api/v1/uploads/
  xsrf_cookies: True
  auto_reload: True
  jwt_expire: 7*24*3600
  public_key:
  private_key:
  aes_key:
  aes_iv:

middleware:

database:
  hostname: 172.22.16.146
  port: 3306
  database: crawlkeeper
  username: root
  password: "!QAZse4@W3a?"